# Generated by Django 4.1.1 on 2022-09-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='search_title',
            field=models.TextField(default='type what to search'),
        ),
    ]
