# Generated by Django 4.1.1 on 2022-09-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_search_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='search',
            new_name='searchs',
        ),
    ]
