# Generated by Django 4.1.1 on 2022-09-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_searchs_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchs',
            name='count',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=100),
        ),
    ]
